[server]
host = "0.0.0.0"
port = 8000

[monitor]
enabled = true
list_interval_seconds = 30
core_interval_seconds = 15
aux_interval_seconds = 30
max_backoff_seconds = 300

fixtures = [
  "d4vguyrwop1mcc3d9a9ox280k",
  "cq1wnjypozp0xc3b1z3b2hlp0",
]
